[tool.poetry]
name = "python-project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.2.2"  # Добавляем pytest для тестирования
flake8 = "^7.1.0"  # Добавляем flake8 для линтера
black = "^24.4.2"  # Добавляем black для форматирования кода
isort = "^5.13.2"  # Добавляем isort для сортировки импортов
pytest-cov = "^5.0.0" # Для отчета о покрытии тестами

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Конфигурация для Black (форматер)
[tool.black]
line-length = 119
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | \.idea
  | __pycache__
)/
'''

# Конфигурация для isort (сортировщик импортов)
[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

# Конфигурация для Flake8 (линтер)
[tool.flake8]
max-line-length = 119
exclude =".git,__pycache__, .venv,venv"
